<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_ValiderEtVerifierLaSuiteDeMaSaisie_3sur4</name>
   <tag></tag>
   <elementGuidId>ce9a91ef-0636-4541-b5f8-b6eb78dbc6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-accordiontab-12-content&quot;]/div/app-actions-bar/div/div[2]/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
