<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_ValiderEtVerifierLaSuiteDeMaSaisie_2sur4</name>
   <tag></tag>
   <elementGuidId>f4ca428a-9b74-4e5b-aee5-a67ead0b4536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-accordiontab-11-content&quot;]/div/app-actions-bar/div/div[2]/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
