<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_JeSolliciteRenouvellementDeMonTitre</name>
   <tag></tag>
   <elementGuidId>da6da6ea-72a3-40a0-ae28-0418f00ab91e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-declaration-pvd/div/div[3]/app-confirmation-pvd/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
