<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_DemandeurContacte</name>
   <tag></tag>
   <elementGuidId>b540fdf8-6eaf-4a4a-b2d6-a0afb4f9a990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-layout/div/div/div/app-navigation-layout/div[2]/app-demande-instruction/div/div[1]/form/p-accordion/div/p-accordiontab[9]/div[2]/div/div/div[2]/anef-input-check/div/div/p-checkbox/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
