<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AccepterLeDocumentCopieMotifDeSejour</name>
   <tag></tag>
   <elementGuidId>0914f6c0-ed4a-473d-bafd-c6c4771fc9f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/app-motif-sejour-visiteur/div/div[2]/div/app-justificatifs/div/div[2]/div/div[2]/anef-input-radio/div/div/fieldset/div/div[2]/p-radiobutton/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
