<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Value_MotifCloturerLaDemande</name>
   <tag></tag>
   <elementGuidId>adef4eda-bf1c-42fa-bfc2-46492313ff1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;motif_cloture&quot;]/div/div[5]/div/ul/p-dropdownitem[2]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
