<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Value_MoisPriseEmpreinte</name>
   <tag></tag>
   <elementGuidId>b2d6e98d-ca9f-4850-b0f0-334a0afc6acb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mois_prise_empreinte&quot;]/div/div[5]/div/ul/p-dropdownitem[3]/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
