<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__5a4bdcee-dc2b-281a-d620-0208f5939b31</name>
   <tag></tag>
   <elementGuidId>5bbbb3bf-0a32-4c6b-ae0d-12769629b735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='5a4bdcee-dc2b-281a-d620-0208f5939b31']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5a4bdcee-dc2b-281a-d620-0208f5939b31</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6ec4284-6f2c-4c40-8c5c-00b589369116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-input connection-input no-spin ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>1024e48f-95b1-43e1-be1c-24d0ff12defe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>card-input connection-input no</value>
      <webElementGuid>1b475197-7a8d-4a10-bb95-f1447cc14b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>f837e029-bd55-48ca-901d-d4520ed2a567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16db50d9-9fa5-4381-ab17-7ff01c2ad080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>5a4bdcee-dc2b-281a-d620-0208f5</value>
      <webElementGuid>9b959936-5176-48b9-ab79-afd2a6b77eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>00237a47-a108-4de3-95e1-5b977ec8ad89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5a4bdcee-dc2b-281a-d620-0208f5939b31</value>
      <webElementGuid>7c055d56-73e5-46c2-9a97-a28479d8f196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>5a4bdcee-dc2b-281a-d620-0208f5939b31-help</value>
      <webElementGuid>2cc99fd8-ac9e-4a7e-89c6-542488102063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>81f12c7c-7065-462c-9815-be3c1eaf9193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5a4bdcee-dc2b-281a-d620-0208f5939b31&quot;)</value>
      <webElementGuid>087beaf9-5c95-449e-944a-c0714f1b2806</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='5a4bdcee-dc2b-281a-d620-0208f5939b31']</value>
      <webElementGuid>f9b133b7-2226-42bc-bc7a-c58c7c8b7207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-input[2]/div/div/input</value>
      <webElementGuid>1f456113-0fe6-41b7-ba90-3e8211f9fbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = '5a4bdcee-dc2b-281a-d620-0208f5939b31']</value>
      <webElementGuid>2928c880-438c-4214-b207-357aeedc3c3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
