<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exemple  9999999999_ef8f9cb9-8c23-1bc_d05766</name>
   <tag></tag>
   <elementGuidId>cb10d9c4-150a-481c-8087-3ce87ba07929</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'email' and @id = 'ef8f9cb9-8c23-1bc8-b913-2b47d7f34147']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ef8f9cb9-8c23-1bc8-b913-2b47d7f34147']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ef8f9cb9-8c23-1bc8-b913-2b47d7f34147</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2f98cf2-a242-4c80-afde-68582fc4e3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-input connection-input no-spin ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>a90d86bf-ca9a-4a33-889d-fea462327b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>card-input connection-input no</value>
      <webElementGuid>4331e1be-e1bd-426e-9e11-e04e8eda9d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>4ef97462-2d31-4a2e-b31c-601dc8d3c9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>195edce6-15d4-4527-bc7d-fd2eb66d0242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>ef8f9cb9-8c23-1bc8-b913-2b47d7</value>
      <webElementGuid>59887876-44e1-45c1-89b5-92437b0f8533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ea00a6b4-afa9-4b02-a3fc-9c279b204fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ef8f9cb9-8c23-1bc8-b913-2b47d7f34147</value>
      <webElementGuid>d9faea54-873e-4d9b-927f-954438687bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ef8f9cb9-8c23-1bc8-b913-2b47d7f34147-help</value>
      <webElementGuid>42da1a7d-d31c-4cc4-99b4-ed446210988b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>h</value>
      <webElementGuid>c5b803ec-b4a7-432b-8f6a-8a35201d7ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ef8f9cb9-8c23-1bc8-b913-2b47d7f34147&quot;)</value>
      <webElementGuid>d2e094f9-be28-4d94-ad10-03ca05f177c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ef8f9cb9-8c23-1bc8-b913-2b47d7f34147']</value>
      <webElementGuid>aaa1455f-0f49-43c3-9d71-8fe119360315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9fca4ddd-3bd6-4e2d-b58e-604e0494b973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'ef8f9cb9-8c23-1bc8-b913-2b47d7f34147']</value>
      <webElementGuid>b0fc0c75-3e22-4335-b0cd-4df9aa8d6b0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
