<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_JétaisEtudiantEnFrance_Oui</name>
   <tag></tag>
   <elementGuidId>d94a4ab2-f3ae-4545-8f93-076ba2d4a027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-accordiontab-4-content&quot;]/div/div/div[1]/div/anef-input-radio/div/div/fieldset/div/div[1]/p-radiobutton/div/div[2]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
