<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_DiplomeSanctionnantAuMoins3AnneesEtudesSupérieures_NON</name>
   <tag></tag>
   <elementGuidId>d073110f-73e7-4e5d-94d4-25d622ae9817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-accordiontab-3-content&quot;]/div/div/div[3]/div/div/div/app-indent-wrapper/app-information-relatives-qualification/div/div/div/anef-input-radio/div/div/fieldset/div/div[2]/p-radiobutton/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
