<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_IntituléDuDiplôme</name>
   <tag></tag>
   <elementGuidId>cb732a87-16ec-4ff6-b015-f9b97a1ad228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div[1]/div/div/div/app-indent-wrapper/app-information-relatives-qualification/div/div[1]/div/anef-input-text/div/div/div[1]/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
