<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_NatureEmploiEtLienNatureInnovanteEntreprise</name>
   <tag></tag>
   <elementGuidId>d78c25e8-2a12-460b-bc22-a20e8f149578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@ng-reflect-name=&quot;NATURE_EMPLOI_ET_LIEN&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
