<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_ChoisirFichier_TitreSejourValide</name>
   <tag></tag>
   <elementGuidId>bcfc785a-5ddd-443b-86d6-725de68e6032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-justificatifs-visiteur//app-justificatif-titre-sejour//app-pieces-jointes//span[1]/input|//app-justificatifs-ptsq//app-justificatif-titre-sejour//app-pieces-jointes//span[1]/input|//app-justificatifs/div[2]/div/p-accordion/div/p-accordiontab[1]/div[2]/div/div[1]/div/app-pieces-jointes[1]/div/span[1]/input
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;ui-accordiontab-7-content&quot;]/div/div[1]/div/app-pieces-jointes[1]/div/button/span</value>
      <webElementGuid>9a9e0cc0-485f-4fa9-9e98-3f0c9faf7f9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
