<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_ChoisirFichier_RessourcesSuffisantes</name>
   <tag></tag>
   <elementGuidId>2d17de0a-7ac6-40e1-9338-ac2aaf00a349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-accordiontab-9-content&quot;]/div/div[2]/app-pieces-jointes[4]/div/span[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
