<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_ChoisirFichier_ReleveDeNotes</name>
   <tag></tag>
   <elementGuidId>8e76be24-9581-4a24-a411-b03181943ee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-accordiontab-8-content&quot;]/div/app-pieces-jointes[2]/div/span[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
