<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Le numro de visa ou de titre de sjour_2087fb</name>
   <tag></tag>
   <elementGuidId>c7d0e841-c41e-49a8-b156-c42a84fc2c2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-klass = 'card-input connection-input-to' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#da3af63b-0ff3-ad78-5280-c6a94c10d8e5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='da3af63b-0ff3-ad78-5280-c6a94c10d8e5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca550dac-f727-490e-8241-028c5d523f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-input connection-input-tooltip no-spin ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>17c06ec3-c300-4fc0-8cb1-6479f96c92fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>card-input connection-input-to</value>
      <webElementGuid>13697bd0-9821-415a-9d3d-378c52e6f098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>2010a99d-45eb-41f1-be05-6ddc7d76e4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>20d275c3-53ca-4f6e-a4ba-722bf64ff20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>da3af63b-0ff3-ad78-5280-c6a94c</value>
      <webElementGuid>7ba9802d-e7cc-4dbf-bb9b-0479f0499c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4119ac88-534e-43e8-9f23-552ad3559c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>da3af63b-0ff3-ad78-5280-c6a94c10d8e5</value>
      <webElementGuid>d764f2a4-1c3f-42bb-b7c8-1cd5edcb6d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>da3af63b-0ff3-ad78-5280-c6a94c10d8e5-help</value>
      <webElementGuid>36bb805d-1627-4f19-99c5-e7b0ea463cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Le numéro de visa ou de titre de séjour est composé de 9 chiffres.</value>
      <webElementGuid>b3486d9c-d069-48b2-b5a5-f46565cb9586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5b948564-a3b2-40ff-b9a6-6a2594034d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;da3af63b-0ff3-ad78-5280-c6a94c10d8e5&quot;)</value>
      <webElementGuid>9c00daad-1dea-46f8-97d3-b4b8790e4e15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='da3af63b-0ff3-ad78-5280-c6a94c10d8e5']</value>
      <webElementGuid>a4e1ba66-68b3-4190-9fa6-25f50d18f0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3907306f-8b96-4e59-8e27-49faf20d591d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'da3af63b-0ff3-ad78-5280-c6a94c10d8e5' and @placeholder = 'Le numéro de visa ou de titre de séjour est composé de 9 chiffres.']</value>
      <webElementGuid>eca1de02-b2a4-4bb2-bb5a-7bfa20ce86f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
