<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jour_ng-untouched ng-pristine ng-valid</name>
   <tag></tag>
   <elementGuidId>8208118d-4186-4701-9863-8e823077fdcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>189acd66-f519-4c34-bd9d-6afb687c96e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2adb8825-b33e-48a8-be6f-0c71d7cce8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{1,2}</value>
      <webElementGuid>a71a1016-5ddb-4554-81e5-b4e6522f1eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ad442ed5-7f9e-44e1-afce-51d12588b12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7dbffe17-de33-4cf4-ac04-6e9bb784130a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>[0-9]{1,2}</value>
      <webElementGuid>e2fc65f5-559d-48fa-a9b4-f00a08d003e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>JJ</value>
      <webElementGuid>4708174b-af33-4e3d-85ba-852002d5f478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0fbcac4e-06af-4aeb-a7d6-6b304661581d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;container-fluid&quot;]/app-root[1]/div[@class=&quot;app-root&quot;]/app-root[@class=&quot;ng-star-inserted&quot;]/main[1]/app-registration[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card-connection-registration keycloakparents&quot;]/div[@class=&quot;registration&quot;]/app-identification[1]/form[@class=&quot;row ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-date[1]/fieldset[@class=&quot;date-component&quot;]/div[@class=&quot;date&quot;]/div[@class=&quot;day&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>ae1d706a-6bfd-41a3-b8af-ea073b81a989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>86343e58-1f1f-4f46-b654-7c3e8d1b68f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9741fb09-6633-462f-aabb-2707e4985a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'JJ']</value>
      <webElementGuid>1a4b701e-b7d8-4f52-b660-dcace6202bd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
