<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SE CONNECTER</name>
   <tag></tag>
   <elementGuidId>f1ca8530-d5cc-49a1-8f74-472861f4487b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='connexion_link']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'connexion_link' and (text() = 'SE CONNECTER' or . = 'SE CONNECTER')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connexion_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>675e46a1-b449-4af6-88b2-f7c3e4d09c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connexion_link</value>
      <webElementGuid>e1722c08-b492-4c38-b7f0-b1e4166dbab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5854b202-cddc-4050-8ea4-74082025a1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>d13b3c27-8885-474a-a661-2a312bf5c0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SE CONNECTER</value>
      <webElementGuid>b8c90eb1-ac30-40db-af0e-88a8466be51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connexion_link&quot;)</value>
      <webElementGuid>6255e957-8d18-4cea-b45c-81edfbe5a06a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='connexion_link']</value>
      <webElementGuid>f5cceb08-3b05-4bf5-bfb9-28119400d97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-nav-new[@id='navBar-new']/nav/div[3]/div/div/ul/li/a/span[2]/a</value>
      <webElementGuid>853d1004-bfb9-4c4e-b9d7-55d7460c9395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SE CONNECTER')]</value>
      <webElementGuid>06795691-1e9b-4622-a0bd-9a33d6439e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acheter un timbre fiscal'])[1]/following::a[2]</value>
      <webElementGuid>a1a9af4e-9586-4eaf-9949-3523e63a0fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demander un document de voyage'])[1]/following::a[3]</value>
      <webElementGuid>6f49d166-bcb7-42ed-8b66-812a964c3fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Étrangers en France : Accueil'])[1]/preceding::a[1]</value>
      <webElementGuid>689dc988-815c-4b26-85f6-0b39c45b9dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Je valide mon VLS-TS'])[1]/preceding::a[1]</value>
      <webElementGuid>8d9b6103-badf-428c-994f-ba998fbfa4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SE CONNECTER']/parent::*</value>
      <webElementGuid>4f1a8c97-1271-4241-9fc5-b6b053e3bb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a</value>
      <webElementGuid>3e636b84-6d86-40d1-a7b9-31f4d55d5bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'connexion_link' and (text() = 'SE CONNECTER' or . = 'SE CONNECTER')]</value>
      <webElementGuid>ab2b5e45-ca9d-4221-99be-3ea3fa66cca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
